---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: product-catalog-lab3
    provider: fabric8
    version: 1.0.0
    group: com.redhat.coolstore
  name: product-catalog-lab3
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: product-catalog-lab3
    provider: fabric8
    group: com.redhat.coolstore
