apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
          env:
          - name: AMQP_SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: kcb-camel-amq-config
                key: service.host2
          - name: AMQP_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: kcb-camel-amq-config
                key: service.port.amqp2
          - name: AMQP_PARAMETERS
            value: transport.trustAll=true&transport.verifyHost=false&amqp.idleTimeout=120000