---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: product-catalog-lab3
    provider: fabric8
    version: 1.0.0
    group: com.redhat.coolstore
  name: my-database-secret
stringData:
  user: luke
  password: secret
